### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by iDoka** [cyrozap/openocd-xilinx-loader#1]
I would like to add more new Xilinx family, but I don't know how to do it.

Is ability to work with new Xilinx family defined by this repo or dependent of OpenOCD contribution?
(I suppose files like `xilinx-xc6s.cfg` and `xc6s.tap` supplied OpenOCD contributors)

**Comment by cyrozap** [comment]
I'm closing this issue since I'm archiving this project.

If you want to program Xilinx FPGA's, you really should just be using OpenOCD. I wrote this code as a hack to load bitstreams into FPGA's during a time that OpenOCD's native support for FPGA programming (using certain programmers) was broken. The issues in OpenOCD have since been fixed, so if you want to use it to program devices that it doesn't support yet, you should add that support to OpenOCD.
